platform :ios,'7.0'
pod 'TSMessages'
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'AFNetworking', '~> 2.4.1'
pod 'Masonry', '~> 0.5.2'
pod 'SDWebImage', '~> 3.6'
pod 'LinqToObjectiveC', '~> 2.0.0'
pod 'MBProgressHUD'
pod 'Mantle'
pod 'FMDB'
pod 'SWTableViewCell'
pod 'UIColor-HexString'
pod 'RBStoryboardLink'